const Functional_KEYWORD = {
    Detail : "详情",
    Edit : "编辑",
    OperationLog : "操作日志",
    CREATE_SUCCESS : "新增成功",
    EDIT_SUCCESS : "编辑成功",
    IMPORT_SUCCESS : "导入成功",
    IMPORT_FAIL_RE : "导入失败，请重试",
    LOGIN_FAIL : "登录失败",
    IMAGE_INSERT_FAIL : "图片插入失败"
}
const EditLog_KEYWORD = {
    SN : "序号",
    EditItem : "编辑项目",
    EditType : "编辑类型",
    BeforeEditing : "编辑前",
    AfterEditing : "编辑后",
    SubmissionTime : "提交时间",
    Editor : "编辑人",
    OperationLog : "操作日志",
    MonthSalary : "薪资月份",
    AVAILABLE_DATE:"有效开始月份"
}
const KEYWORDS = {
    SN:"序号",
    SalaryMonth:"薪资月份",
    employeeID:"员工编号",
    EnglishName:"英文名",
    Department:"部门",
    Group:"组别",
    WORK_POSITION:"职位",
    NATIONAL:"国籍",
    Rank:"职级",
    CURRENT_RANK:"目前职级",
    ADJUSTED_RANK:"调整后职级",
    ScheduleDate:"排班日期",
    ScheduleTime:"排班时间",
    OfficeAddress:"办公地址",
    OfficeFloor:"办公楼层",
    Office:"办公室",
    TotalAmount_PHP:"总金额(PHP)",
    Amount_PHP:"金额(PHP)",
    Amount_CNY:"金额(CNY)",
    Status:"状态",
    SalaryDistributionMethod:"薪资派发方式",
    DistributionDate:"派发日期",
    Operating:"操作",
    Export:"导出",
    Import:"导入",
    Detail:"详情",
    Edit:"编辑",
    OperationLog:"操作日志",
    totalAmount:"总金额",
    Cash:"现金",
    ATC:"ATC",
    BankCard:"银行卡",
    NoPayment:"不发薪",
    ATCAccount:"ATC账号",
    ATCMobile:"ATC手机号码",
    Remark:"备注",
    BankName:"银行名称",
    _pinyin:"拼音",
    BankAccount:"银行账号",
    BankCardNumber:"银行卡号",
    Reason:"原因",
    ChoiceDate:"选择日期",
    unPaid:"待发放",
    paid:"已发放",
    TotalAmount:"总金额",
    Details:"详情",
    Keyword:"关键字",
    year:"年",
    month:"月",
    search:"搜索",
    All:"全部",
    FullSalaryPayment:"全部薪资",
    CURRENT_SALARY_PHP:"目前薪资（PHP）",
    ADJUSTED_SALARY_PHP:"调整后薪资（PHP）",
    ADJUSTED_SALARY_CNY:"调整后薪资（CNY）",
    ROOM_SUBSIDY:"房补",
    ROOM_SUBSIDY_PHP:"房补（PHP）",
    ROOM_SUBSIDY_CNY:"房补（CNY）",
    FOOD_SUBSIDY_PHP:"餐补（PHP）",
    FOOD_SUBSIDY_CNY:"餐补（CNY）",
    COUNTED_AMOUNT_CNY:"合计（CNY）",
    DISTINCT_ORIGINAL_SALARY_LESS:"对比原底薪减少金额",
    ACTIVE_DATE:"生效日期",
    CashPayment:"现金发放",
    ATCPayment:"ATC发放",
    BankCardPayment:"银行卡发放",
    AmountOfPeoeple:"总人数",
    AmountOfPeoeple_append:"根据各级人数相加得出",
    Employee_A:"A级员工",
    Employee_B:"B级员工",
    Employee_C:"C级员工",
    Employee_T:"T级员工",
    Employee_S:"S级员工",
    Employee_M:"M级员工",
    Leave:"离职",
    SalaryAmount:"薪资总计",
    SalaryAmount_PHP:"薪资总计(PHP)",
    SN_en:"NO.",
    EmployeeID:"员工编号",
    EmployeeID_en:"Employee ID",
    Department_en:"Department",
    EnglishName_en:"English name",
    _pinyin_en:"Pinyin",
    EntryDate:"入职日期",
    EntryDate_en:"On board date",
    ConversioDate:"转正日期",
    ConversioDate_en:"Actually date of regularization",
    PWP_IssuanceDate:"PWP签发日",
    PWP_IssuanceDate_en:"PWP Issued Date",
    PWP_ExpirDate:"PWP到期日",
    PWP_ExpirDate_en:"PWP Expiry Date",
    PWP_Type:"PWP类型",
    PWP_Type_en:"PWP type",
    TinNumber:"Tin number",
    Use_AEP:"With AEP",
    FingerPrint:"Finger print",
    Acr_Icard:"With Acr Icard",
    _9G_IssueDate:"9G 签发日",
    _9G_IssueDate_en:"9G order issue date",
    _9G_ExpiryDate:"9G 到期日",
    _9G_ExpiryDate_en:"9G order expiry date",
    _9G_Type:"9G 类型",
    _9G_Type_en:"9G/AEP type",
    Remarks:"备注",
    Remarks_en:"RemarkS",
    WorkingTime:"在职时间",
    WorkingTime_en:"Period of hired",
    PassportCustody:"护照保管",
    PassportCustody_en:"Passport Custody",
    _9G_Status:"9G状态",
    _9G_Status_en:"9G status",
    Operating_en:"edit",
    EditItem:"编辑项目",
    BeforeEditing:"编辑前",
    AfterEditing:"编辑后",
    SubmissionTime:"提交时间",
    Editor:"编辑人",
    IssueNumber : "事项编码",
    TYPE:"类型",
    Submitter:"提交人",
    Submitter_Department:"提交人部门",
    TransferMethod: "结算方式",
    SETTLEMNET_MONTH_START:"开始结算月",
    SETTLEMNET_MONTH_END:"截止结算月",
    CURRENT_STATUS:"目前状态",
    IS_REGULAR_POSITION:"是否转正",
    STARTED_WORK_YEARS_DATE:"工龄起始日期",
    WORK_YEARS:"工龄",
    POSTION_TYPE_OF_EXAMINE:"评估类型",
    DELAY_OF_MONTH:"延迟月份"
 }
export {     
    EditLog_KEYWORD,
    Functional_KEYWORD,
    KEYWORDS
}